services:
  node-js:
    build: ./node-js
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    labels:
      - "job=nodejs"

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    labels:
      - "logging=promtail"
      - "job=loki"
    # volumes: # 沒有 volume 時候資料會儲存於 loki 的 filesystem 內部，
    #          # 但是一旦 container 重啟，資料就會消失，因為是 mvp 的設計，
    #          # 所以並未掛載 volume
    #   - loki-data:/loki # production 時候需要加上 volume 才能儲存資料
  promtail:
    image: grafana/promtail:latest
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    depends_on:
      - loki
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
